server:
  port: 8000
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: /etc/letsencrypt/keystore.p12
#    key-store-password: codingisgood

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/**

        - id: content-service
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/api/content-service/**

        - id: group-service
          uri: lb://GROUP-SERVICE
          predicates:
            - Path=/api/group-service/**

        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/api/game-service/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notification-service/**

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,prometheus
#  metrics:
#    export:
#      prometheus:
#        enabled: true
#  endpoint:
#    prometheus:
#      enabled: true
#    health:
#      show-details: always
